### ISSUE TITLE
Asciiflow 3 updates?

### ISSUE THREAD

**Issue by vashnt707** [lewish/asciiflow#150]
Would very much love to see Asciiflow 3.

**Comment by Qix-** [comment]
I would too :) Prepare yourself for a long-ish post since I'm sure a number of people would be interested in an update aside from yourself.

Skip to below the line for at-a-glance goals and updates.

I mentioned in another comment but since this issue is asking specifically about v3 I should post more of a complete update here.

About a year and a half ago, @lewish handed the project over to me. It was, and still very much is, my intention to introduce a rewrite of the project to fix a number of issues not easily doable in the current codebase.

This included (but isn't limited to) the various "magic" border bugs (certain sequences of characters being treated as borders or arrows), double-wide characters/RTL support (Chinese, Japanese, Arabic, etc.), non-ASCII rendering _and_ output (e.g. Unicode box characters and custom arrow tips), etc.

Further, it would re-think how objects are laid out, treating things on the canvas more like individual entities rather than algorithmically determining what is and isn't a border/arrow/etc. based purely on the characters themselves.

It also had refresh of the visual design.

Shortly after the project was handed over, I had a number of things happen in my personal life that stole almost all of my free time away from me and I'm just _now_ getting some of that free time back (I had just completed a trans-Atlantic relocation and a number of things went wrong that I needed to devote attention toward).

However, rest assured this is still very much a project I intend to complete, as Asciiflow is still a tool I use quite frequently.

---

- The new codebase is decently far along, being developed both in the browser as well as Electron. It will be hosted at the same URL and I will eventually discuss additional means of distribution for those that would like it.
- It already supports classic ASCII characters as well as other charactersets, and I intend to make all special characters configurable and hot-swappable.
- Visual depiction and rendered output are now identical; the existing codebase could not handle this case without major rewrites.
- The new editor will support "classic" Asciiflow mode (identically to the current functionality) as well as the new object editor, which will solve a number of the strange character transformation bugs we see today (e.g. `<>` turning into `<>`, or `-|` turning into `-x`).
- I would _like_ to look into Gist import/export support in lieu of Google drive, though if demand is large enough, proper Google drive support can be added back in (it's historically been kind of a brittle integration).
- I would _like_ to look into non-text rendering of graph images, though I understand this is quite difficult technically. I've seen a number of experiments with it, and there has been some interest in it here in the tracker, so after AF3 is released it might be worth looking into as a "stretch goal".

As for a timeline, I can't give you an honest answer. I have some strict deadlines at the moment but truthfully this is one of the projects that still hangs over my head even today.

It will happen, just not as quickly as anyone would have liked. For that, I apologize.

Any other questions can be posted here - I'm always happy to have the discussion. 🙂 

Thanks for asking!

**Comment by jaredkhan** [comment]
@Qix- Is AF3 open to contributors? It's sounding like a big chunk of work and I have some time I could give this week if it would help.

**Comment by lewish** [comment]
Commenting in here with some updates.

First off, let me apologize to everyone, particularly @Qix- . There are a number of things I've done wrong with this project, and I also have some updates.

- I continually failed to respond to any issues
- I never looked at anyone's PRs
- I did indeed give @Qix-  the green light to go ahead and re-write Asciiflow back in 2018
- I then started re-writing it myself at the start of 2020 because I'm bad at collaborating and things slowed down a little
- I don't / didn't (?) know how to run OSS projects well

With all that said, I've now shipped an beta of what I'm considering AF3.

- A rewrite of the code in TypeScript + React, with Bazel and MobX and Material-UI
- Some proper devtooling infrastructure so it's easier to contribute and deploy (this was a manual, annoying process before and)
- A bunch of new features including:
- LocalStorage file system instead of GDrive integration
- A move toward Ascii box drawing characters to resolve some of the many issues @Qix- mentions above
- Dark mode
- Better export tooling, comment blocks
- Better help content and more modern key bindings

I hope this all serves as a good base for us to move forward with this project. Additionally, I hope that people are happy sending PRs going forward, I have more time now to look at them now, they should get deployed to asciiflow.com automatically after merge, and I've added @Qix- to project owners (if anyone would like to be more actively involed, please let me know!).

**Comment by vashnt707** [comment]
Awesome!!! Fantastic upgrade 😃

**Comment by Qix-** [comment]
Hey going to go ahead and close this to tidy up a bit - let me know if there's anything left undecided here that I might have missed!

**Comment by Sieboldianus** [comment]
> I would like to look into Gist import/export support in lieu of Google drive

It would be great to have some way to version changes in git.
