### ISSUE TITLE
Export to C comment

### ISSUE THREAD

**Issue by pengi** [lewish/asciiflow#65]
I use this tool to document small state-machines inlined with some C code (or other code). Thus, I would like to be able to export to a comment.

Importing isn't that problem though, since it's possible to do box removal.

During exporting, I would like to get something like:

```
/*
 *  +----------+
 *  | A state  |
 *  +--^----+--+
 *     |    |
 *     |    |
 *  +--+----v--+
 *  | machine  |
 *  +----------+
 */
```

**Comment by MikeWeller** [comment]
I would also like this feature, but with support for multiple comment styles: `//`, `#`, `/* ... */` etc.

**Comment by Qix-** [comment]
These days it's pretty common to have multi-cursor support. In Vim, for example, I can do Ctrl+V to get box selection mode going and insert a comment or indentation around a diagram quickly.

![kapture 2019-02-11 at 20 33 07](https://user-images.githubusercontent.com/885648/52588228-4d38e300-2e3c-11e9-93e9-85acf93e8af1.gif)


The same goes for Sublime, Atom, and a slew of other editors - not to mention find+replace can generally use regexes to do replacements, meaning you can replace `^` with `  * ` in order to insert the indentation and comment asterisk on each line.

Is this still a must-have?

**Comment by Qix-** [comment]
Yes, @qix-, this would be helpful.

Tagging as an enhancement for AF3. Sorry for the noise 4 years later.

**Comment by lewish** [comment]
This is now supported for export in the latest version:

![image](https://user-images.githubusercontent.com/912458/110206010-3c1ffc00-7e73-11eb-8229-eed314a416e5.png)

And supports a few different comment types:

![image](https://user-images.githubusercontent.com/912458/110206018-49d58180-7e73-11eb-9a73-df7fccf9fe8c.png)
